spring:
  application:
    name: easy-log
  profiles:
    active: dev

server:
  port: 80

logging:
  # 日志文件地址
  config: classpath:logback-spring.xml
  # 配置Logstash地址
  logstash:
    address: 192.168.42.128:9400
  level:
    root: info

